[package]
name = "tungsten-mc"
version = "0.1.0"
edition = "2021"
authors = ["Niek Aukes"]
description = "Minecraft worldgen runtime library with optimized implementations of density functions, noise generators, and utility functions"
license = "MIT OR Apache-2.0"
repository = "https://github.com/NiekAukes/tungsten-frontends"
readme = "README.md"
keywords = ["minecraft", "worldgen", "noise", "perlin", "density"]
categories = ["game-engines", "algorithms"]
exclude = [
    "target/",
]

[build-dependencies]
tungsten-mc-compile = "0.1.0"

[dependencies]
md5 = "0.7.0"
bytemuck = { version = "1", features = ["derive"] }
pollster = "0.4"
rayon = "1.12.0"
